bookstore/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path(
        '', views.index, name='index'
    ),
    path(
        'catalog', views.catalog, name='catalog'
    ),
    path(
        'news', views.news, name='news'
    ),
    path(
        'change_favorite', views.change_favorite, name='change_favorite'
    ),
    path(
        'change_cart', views.change_cart, name='change_cart'
    ),
    path(
        'search', views.search, name='search'
    ),
    path(
        'book/<int:book_id>/', views.book_detail, name='book'
    ),

]

bookstore/bookstore/urls.py
from django.conf import settings
from django.views.static import serve as mediaserve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('my/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

bookstore/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path(
        'login', views.login, name='login'
    ),
    path(
        'logout', views.logout, name='logout'
    ),
    path(
        'signup', views.signup, name='signup'
    ),
    path(
        'favorite', views.favorite, name='favorite'
    ),
    path(
        'review/<int:book_id>/', views.create_review, name='review'
    ),
    path(
        'review/<int:book_id>/<int:review_id>/',
        views.change_review,
        name='change_review'
    ),
    path(
        'profile', views.profile, name='profile'
    ),
    path(
        'cart', views.cart, name='cart'
    ),
    path(
        'cart/<int:buy>/', views.cart, name='cart'
    ),
    path(
        'take_cart_img', views.take_cart_img, name='take_cart_img'
    ),
    path(
        'payment', views.payment, name='payment'
    ),
    path(
        'library', views.library, name='library'
    ),
    path(
        'get_book/<int:book_id>/<str:format>', views.get_book, name='get_book'
    ),
]

bookstore/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
import re


User = get_user_model()


class TextInputWithoutValue(forms.TextInput):
    def format_value(self, value):
        return None


class EmailInputWithoutValue(forms.EmailInput):
    def format_value(self, value):
        return None


class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )


class ChangeForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        """Запоминаем пользователя для валидации"""
        super(ChangeForm, self).__init__(*args, **kwargs)
        self.instance = kwargs['instance']

    password = forms.CharField(
        label=("Пароль"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=False
    )
    password2 = forms.CharField(
        label=("Подтверждение пароля"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=False
    )

    class Meta(UserChangeForm.Meta):
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password'
        )

    def clean(self):
        """Валидация пароля, почты и ника"""
        username = self.cleaned_data["username"]
        email = self.cleaned_data["email"]
        first_name = self.cleaned_data["first_name"]
        last_name = self.cleaned_data["last_name"]
        if re.search(r'[^а-яА-ЯёЁ]', first_name):
            raise ValidationError(
                {"first_name": 'Имя должно содержать только русские буквы!'}
            )
        if re.search(r'[^а-яА-ЯёЁ]', last_name):
            raise ValidationError(
                {"last_name": 'Фамилия должна содержать только русские буквы!'}
            )
        if self.instance.username != username:
            UserCreationForm.clean_username(self)
        password1 = self.cleaned_data["password"]
        password2 = self.cleaned_data["password2"]
        if self.instance.email != email:
            if User.objects.filter(email=self.cleaned_data['email']).exists():
                raise ValidationError(
                    {"email": 'Пользователь с такой почтой уже существует!'}
                )
        if password1 or password2:
            if password1 != password2:
                raise ValidationError(
                    {"password": 'Пароли не совпадают',
                     "password2": 'Пароли не совпадают'}
                )
        else:
            del (self.cleaned_data["password"])
            del (self.cleaned_data["password2"])
        return self.cleaned_data

bookstore/users/views.py
import django.contrib.auth as auth
from django.template.response import TemplateResponse
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core.mail import send_mail
from http import HTTPStatus
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponseRedirect
import uuid
from django.core.paginator import Paginator
from yookassa import Payment
from datetime import date

from books.models import Book
from books.views import catalog_type, main_forms
from .forms import SignupForm, ChangeForm
from .models import Review, Order
from bookstore.settings import MAX_ORDERS_PROFILE, EMAIL_HOST_USER, DOMEN


def signup(request):
    """Регистрация"""
    if request.method == "POST":
        form = SignupForm(request.POST, auto_id='signup_%s')
        if form.is_valid():
            new_user = form.save()
            auth.login(request, new_user)
            return JsonResponse(status=HTTPStatus.OK, data={'login': True})

        context = {
            'signup_form': form
        }
        return TemplateResponse(request, 'dynamic_forms/signup.html', context)
    return reverse_lazy('books:index')


def login(request):
    """Вход в аккаунт"""
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():

            auth.login(request, form.get_user())
            return JsonResponse(status=HTTPStatus.OK, data={'login': True})

        context = {
            'auth_form': form
        }
        return TemplateResponse(request, 'dynamic_forms/auth.html', context)
    return reverse_lazy('books:index')


@login_required
def logout(request):
    """Выход из аккаунта"""
    auth.logout(request)
    return redirect('books:index')


@login_required
def favorite(request, sort='buying'):
    """Каталог избранного"""
    books_list = request.user.favorite_books.all()
    context = catalog_type(request, books_list, sort, True, True)
    return TemplateResponse(request, 'users/favorite.html', context)


@login_required
def create_review(request, book_id):
    """Создание нового отзыва"""
    book = get_object_or_404(Book, id=book_id)
    user = request.user
    if request.method == 'POST' and not book.review.filter(user=user).exists():
        data = request.POST
        score = int(data['score'])
        if 0 >= score > 5:
            score = 5
        Review.objects.create(
            user=user,
            book=book,
            comment=data['text'],
            score=score
        )
        if book.review.all():
            score_list = [review.score for review in book.review.all()]
            book.score = sum(score_list) / len(score_list)
            book.save()
        return JsonResponse(status=HTTPStatus.OK, data={})
    return redirect('books:book', book_id=book_id)


@login_required
def change_review(request, book_id, review_id):
    """Изменение или удаление отзыва"""
    book = get_object_or_404(Book, id=book_id)
    review = Review.objects.filter(id=review_id)
    if request.method == 'POST' and review:
        data = request.POST
        if 'delete' in data:
            review.delete()
        else:
            score = int(data['score'])
            if 0 >= score > 5:
                score = 5
            review.update(
                comment=data['text'],
                score=score
            )
        if book.review.all():
            score_list = [review.score for review in book.review.all()]
            book.score = sum(score_list) / len(score_list)
        else:
            book.score = 0
        book.save()
    return redirect('books:book', book_id=book_id)


@login_required
def profile(request):
    """Профиль"""
    user = request.user
    change_form = ChangeForm(instance=user)
    orders = user.order.filter(close=True)
    paginator = Paginator(orders, MAX_ORDERS_PROFILE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    orders_amount = []
    amount = 0
    for order in page_obj:
        for book in order.book.all():
            amount += book.price * (100 - book.discount) / 100
        orders_amount.append(amount)
    if request.method == 'POST':
        data = request.POST
        change_form = ChangeForm(
            data=data, instance=user)

        if change_form.is_valid():

            change_form = change_form.save(commit=False)
            change_form.save()
            if data['password']:

                user.set_password(data['password'])
                user.save()
            return redirect('books:index')

    context = {
        'page_obj': page_obj,
        'change_form': change_form,
        'orders_amount': orders_amount
    }
    context.update(main_forms(request))
    return TemplateResponse(request, 'users/profile.html', context)


@login_required
def cart(request, buy=0):
    """Корзина.
    buy влияет на вывод модального окна после оплаты:
    0 - пользователь не перенаправлен с оплаты,
    1 - пользователь вернулся с оплаты не оплатив,
    2 - пользователь вернулся с оплаты оплатив"""
    books_order = request.user.order.get(close=False).book.all()
    price = sum(books_order.annotate(
        total_price=(F('price') * (100 - F('discount'))) / 100
    ).values_list('total_price', flat=True))

    context = {
        'books_order': books_order,
        'price': price,
        'buy': buy
    }
    context.update(main_forms(request))
    return TemplateResponse(request, 'users/cart.html', context)


def take_cart_img(request, order_full=False):
    if request.user.is_authenticated:
        order_full = request.user.order.get(close=False).book.all().exists()
    return TemplateResponse(
        request, 'includes/cart_img.html', {'order_full': order_full}
    )


@login_required
def payment(request):
    """Процесс оплаты и проверка что оплата успешна.
    id платежа встраивается в order.
    Если оплата неуспешна, id удаляется и создается новая оплата"""
    user = request.user
    order = user.order.filter(close=False)[0]
    if order.payment:
        if 'succeeded' == Payment.find_one(order.payment).status:
            html_message = (f'Вы успешно оплатили заказ на '
                            f'<a href="{DOMEN}">сайте</a>!<br>'
                            'Нажмите на формат для скачивания книги:<br><br>')
            for book in order.book.all():
                user.buyed_books.add(book)
                html_message += f'{book.name}:<br>'
                for file in book.files.all():
                    html_message += (f'&emsp;<a href="{DOMEN}{file.file.url}">'
                                     f'{file.name}</a><br>')
            send_mail(subject=f'Заказ #{user.id}-{order.id} оплачен',
                      message=None,
                      from_email=EMAIL_HOST_USER,
                      recipient_list=[user.email],
                      html_message=html_message)
            order.close = True
            order.close_data = date.today()
            Order.objects.create(user=user)
            book.buying += 1
            book.save()
            buy = 2
        else:
            order.payment = ''
            order.amount = 0
            buy = 1
        order.save()
        return redirect('users:cart', buy=buy)
    price = sum(order.book.annotate(
        total_price=(F('price') * (100 - F('discount'))) / 100
    ).values_list('total_price', flat=True))
    payment = Payment.create({
        "amount": {
            "value": f"{float(price)}",
            "currency": "RUB"
        },
        "confirmation": {
            "type": "redirect",
            "return_url": f'{DOMEN}/my/payment'

        },
        "capture": True
    }, uuid.uuid4())
    order.payment = payment.id
    order.amount = price
    order.save()
    return HttpResponseRedirect(payment.confirmation.confirmation_url)


@login_required
def library(request):
    """Купленные книги пользователя (библиотека)"""
    context = {
        'buyed_books': request.user.buyed_books.all()
    }
    context.update(main_forms(request))
    return TemplateResponse(request, 'users/library.html', context)


@login_required
def get_book(request, book_id, format):
    """Возвращаем ссылку на запрашиваемый формат файла"""
    book = get_object_or_404(request.user.buyed_books, id=book_id)
    return redirect('../../../' + book.files.all().get(name=format).file.url)

bookstore/templates/users/cart.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block content %}
<script>
    // При нажатии кнопки "Удалить книгу из корзины" товар удаляется из html страницы и из заказа в БД
    $(document).ready(function () {
        $(".delete-book").submit(function () {
            var elem = $(this)
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (html) {
                    var price = Number(document.getElementById("price").textContent);
                    price -= parseInt(elem.find("span[class='book_price']").text())
                    document.getElementById("price").textContent = price
                    elem.remove();
                }
            });
            var form = $('#get_cart_img')
            setTimeout(
                () => {
                    if ($('.delete-book').length < 1) {
                        $.ajax({
                            url: form.attr('action'),
                            success: function (html) {
                                form.replaceWith(html)
                            }
                        });
                        return false;
                    }
                },
                1000
            );
            return false;
        });
    });
</script>
<script>
    // При нажатии кнопки "Удалить книгу из корзины" товар удаляется из html страницы и из заказа в БД
    $(document).ready(function () {
        if (Number('{{ buy }}') > 0) {
            $('#buy_modal_button').click()
        }
    });
</script>
{% if buy == 2 %}
<div id="buy_modal" class="modal fade modal-fullscreen" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body d-flex flex-column align-items-end">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="d-flex flex-column align-items-center mb-5">
                <span style="font-size: 24px; font-weight: 600;">Поздравляем с покупкой!</span>
                <div class="d-flex">
                    <span>Перейдите в</span>
                    <a href="{% url 'users:library' %}" class="mx-1">библиотеку</a>
                    <span>для чтения.</span>
                </div>
            </div>
        </div>
    </div>
</div>
{% elif buy == 1 %}
<div id="buy_modal" class="modal fade modal-fullscreen" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body d-flex flex-column align-items-end">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="d-flex flex-column align-items-center mb-5">
                <span style="font-size: 24px; font-weight: 600;">Что-то пошло не так.</span>
                <span> Попробуйте оформить заказ еще раз.</span>
            </div>
        </div>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col-12" style="min-height: 800px; height: unset;">
        <div class="row">
            <div class="col-12 col-lg-3 mb-5">
                <button id="buy_modal_button" type="button" class="btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#buy_modal" hidden>
                    Launch demo modal
                </button>
                <form id="cart-close" class="background-after" method="post" action="{% url 'users:payment' %}">
                    {% csrf_token %}
                    <div class="d-flex justify-content-between align-items-center">
                        <span style="font-size: 16px; font-weight: 600;">Итого:</span>
                        <div>
                            <span id="price" style="font-size: 20px; font-weight: 400;">{{ price }}</span>
                            <span> ₽</span>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-light mt-2 text-light w-100"
                        style="background-color: #123C69;">Оформить заказ</button>
                </form>
            </div>
            <div class="col-12 col-lg-9 p-3 background-after">
                {% for book in books_order %}
                <form class="row delete-book d-flex rounded-3 mt-3 mx-0"
                    style="border: 2px #123C69 solid; overflow: hidden;" method="post"
                    action="{% url 'books:change_cart' %}">
                    {% csrf_token %}
                    <div class="col-12 col-lg-9 d-flex px-0 " style="background-color: #EEE2DC; height: min-content;">
                        <div class="d-flex justify-content-center mx-4">
                            <a class="rounded-2"
                                style="width: min-content; height: min-content; border: 2px #AC3B61 solid; overflow: hidden; display: flex;"
                                href="{% url 'books:book' book.id %}">
                                <img height="100px" src="{{ book.main_image.url }}">
                            </a>
                        </div>
                        <div class="d-flex justify-content-center align-items-center">
                            <a href="{% url 'books:book' book.id %}">
                                {{ book.name }}
                            </a>
                        </div>
                    </div>
                    <div class="col-12 col-lg-3 d-flex flex-column px-0s justify-content-between">
                        <div class="d-flex justify-content-between align-items-center">
                            <span style="font-size: 16px; font-weight: 600;">Цена:</span>
                            <span class="book_price" style="font-size: 20px; font-weight: 400;">{{ book.get_price }}
                                ₽</span>
                        </div>
                        <button class="btn btn-light w-100 mb-3 text-light" style="background-color: #AC3B61;"
                            type="submit">
                            <span>Удалить из корзины</span>
                        </button>
                        <input name="book" value="{{ book.id }}" hidden>
                    </div>
                </form>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookstore/templates/users/favorite.html
{% extends 'books/catalog.html' %}
{% load static %}
{% block catalog_name %}
Избранное
{% endblock %}
{% block catalog_url %}
{% url 'users:favorite' %}
{% endblock %}

bookstore/templates/users/library.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-12" style="min-height: 800px; height: unset;">
        <div class="row">
            <div class="col-12 p-3 background-after">
                {% for book in buyed_books %}
                <div class="row delete-book d-flex rounded-3 mt-3 mx-0"
                    style="border: 2px #123C69 solid; overflow: hidden;">
                    <div class="col-12 col-lg-8 d-flex px-0 align-items-center" style="background-color: #EEE2DC; ">
                        <div class="d-flex justify-content-center mx-4">
                            <a class="rounded-2"
                                style="width: min-content; height: min-content; border: 2px #AC3B61 solid; overflow: hidden; display: flex;"
                                href="{% url 'books:book' book.id %}">
                                <img height="100px" src="{{ book.main_image.url }}">
                            </a>
                        </div>
                        <div class="d-flex justify-content-center align-items-center">
                            <a href="{% url 'books:book' book.id %}">
                                {{ book.name }}
                            </a>
                        </div>
                    </div>
                    <div class="row col-12 col-lg-4 d-flex flex-column px-0s align-items-center text-center mb-1">
                        <span style="font-size: 16px; font-weight: 600;">Скачивание:</span>
                        <div class="d-flex col-lg-12 justify-content-between row">
                            {% for file in book.files.all %}
                            <div class="col-4 mb-1">
                                <a class="btn" style="background-color: #123C69; min-width: 100%;"
                                    href="{% url 'users:get_book' book.id file.name %}">
                                    <span style="color: #FFF;">{{ file.name }}</span>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

bookstore/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-12 col-lg-4 background-after" style="height: min-content;">
        <form id="form-profile" class="text-center" method="post" action="{% url 'users:profile'%}">
            {% csrf_token %}
            <span class="mp-3" style="font-size: 25px; font-weight: 600;">Личный кабинет</span>
            <div class="mp-1 p-3 rounded-3" style="border: 2px #123C69 solid">
                {% for error in change_form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
                <div class="row">
                    {% for field in change_form %}
                    <div class="col-12 d-flex flex-column mb-4 justify-content-end">
                        {% for error in field.errors %}
                        <div class="alert alert-danger mb-0">
                            {{ error|escape }}
                        </div>
                        {% endfor %}
                        <label class="mb-1" style="font-size: 18px;">{{ field.label }}</label>
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
                <div class="d-flex justify-content-between mt-3">
                    <button type="submit" class="btn btn-light shadow-none border-0">
                        Сохранить
                    </button>
                    <a class="btn shadow-none border-0" href="{% url 'users:logout' %}"
                        style="background-color: #AC3B61;">
                        <span style=" color: white;">
                            Выйти из аккаунта
                        </span>
                    </a>
                </div>
            </div>
        </form>
    </div>
    <div class="offset-0 offset-lg-2 col-lg-6 background-after" style="height: min-content;">
        {% include 'users/includes/orders.html' %}
    </div>
</div>

{% endblock %}