bookstore/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path(
        '', views.index, name='index'
    ),
    path(
        'catalog', views.catalog, name='catalog'
    ),
    path(
        'news', views.news, name='news'
    ),
    path(
        'change_favorite', views.change_favorite, name='change_favorite'
    ),
    path(
        'change_cart', views.change_cart, name='change_cart'
    ),
    path(
        'search', views.search, name='search'
    ),
    path(
        'book/<int:book_id>/', views.book_detail, name='book'
    ),

]

bookstore/bookstore/urls.py
from django.conf import settings
from django.views.static import serve as mediaserve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('my/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

bookstore/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path(
        'login', views.login, name='login'
    ),
    path(
        'logout', views.logout, name='logout'
    ),
    path(
        'signup', views.signup, name='signup'
    ),
    path(
        'favorite', views.favorite, name='favorite'
    ),
    path(
        'review/<int:book_id>/', views.create_review, name='review'
    ),
    path(
        'review/<int:book_id>/<int:review_id>/',
        views.change_review,
        name='change_review'
    ),
    path(
        'profile', views.profile, name='profile'
    ),
    path(
        'cart', views.cart, name='cart'
    ),
    path(
        'cart/<int:buy>/', views.cart, name='cart'
    ),
    path(
        'take_cart_img', views.take_cart_img, name='take_cart_img'
    ),
    path(
        'payment', views.payment, name='payment'
    ),
    path(
        'library', views.library, name='library'
    ),
    path(
        'get_book/<int:book_id>/<str:format>', views.get_book, name='get_book'
    ),
]

bookstore/books/forms.py
from django import forms


class SearchForm(forms.Form):
    search_word = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Поиск',
            'oninvalid': "this.setCustomValidity('Введите слово для поиска')",
            'oninput': "this.setCustomValidity('')"
        }))

bookstore/books/views.py
from django.template.response import TemplateResponse
from django.db.models import Q, F
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from datetime import timedelta, date
from itertools import chain

from .models import Book, Genre, Banner
from .forms import SearchForm
from users.models import Review, ViewedGenres
from users.forms import SignupForm
from bookstore.settings import NEWBOOK_DAYS, MAX_BOOKS_ON_SLIDER


def main_forms(request, order_full=False):
    """Формы ниже используется на всех страницах"""
    user = request.user
    search_form = SearchForm
    auth_form = AuthenticationForm
    signup_form = SignupForm(auto_id='signup_%s')
    if user.is_authenticated:
        order_full = user.order.get(close=False).book.all().exists()

    forms = {
        'search_form': search_form,
        'auth_form': auth_form,
        'signup_form': signup_form,
        'order_full': order_full
    }
    return forms


def filter_books(books_list, data):
    """
    Фильтрация книг
    books_list - список книг,
    data - requst.POST из родительской функции.
    """
    if data.getlist('genres'):
        for search_genre in data.getlist('genres'):
            books_list = books_list.filter(genre=search_genre)
    if data.get('pricemin', '') or data.get('pricemax', ''):
        books_list = books_list.annotate(
            total_price=(F('price') * (100 - F('discount'))) / 100
        ).filter(total_price__range=(
            int(data['pricemin']) if data['pricemin'] else 0,
            int(data['pricemax']) if data['pricemax'] else 9999990
        ))
    if data.get('datemin', '') or data.get('datemax', ''):
        books_list = books_list.filter(release__range=(
            data['datemin'] if data['datemin'] else 0,
            data['datemax'] if data['datemax'] else 9999
        ))
    return books_list


def catalog_type(request, books_list, sort, auth=False, favorite=False):
    """
    Сортировка и фильтрация для каталог-подобных страниц
    request - request из родительской функции,
    books_list - список книг,
    sort - способ сортировки,
    auth - для родительской функции требуется авторизация (@login_required),
    favorite - список избранного = список книг
    """
    data = request.POST
    user = request.user
    filter_dict = {
        'sort': sort
    }
    favorite_books = []
    if (request.method == "POST"
        and books_list
        and 'apply_filter' in data
            and sort):
        sort = data.get('sort', sort)
        books_list = filter_books(books_list, data)
        post_filter_dict = {
            'genres': list(map(int, data.getlist('genres'))),
            'pricemin': data.get('pricemin', ''),
            'pricemax': data.get('pricemax', ''),
            'datemin': data.get('datemin', ''),
            'datemax': data.get('datemax', ''),
        }
        filter_dict.update(post_filter_dict)
    if (not auth and user.is_authenticated) or auth:
        if favorite:
            favorite_books = books_list
        else:
            favorite_books = user.favorite_books.all().values_list(
                'id', flat=True)
    if books_list and sort:
        books_list = books_list.annotate(
            total_price=(F('price') * (100 - F('discount'))) / 100
        ).order_by(
            '-' + sort[4:] if 'min_' in sort else sort
        )

    context = {
        'page_obj': books_list,
        'genres': Genre.objects.all(),
        sort: 'active',
        'filter_dict': filter_dict,
        'favorite_books': favorite_books
    }
    context.update(main_forms(request))
    return context


def index(request):
    """Главная"""
    user = request.user
    popular = Book.objects.all().order_by(
        '-buying')
    new = Book.objects.filter(
        created__gte=date.today() - timedelta(days=NEWBOOK_DAYS))
    recomended = Book.objects.all().order_by('-score')
    favorite_books = None
    if not new:
        new = Book.objects.order_by('created')
    if user.is_authenticated:
        if user.viewed_genres:
            user_recomended = popular.filter(genre=user.most_viewed_genres)
            recomended = list(chain(user_recomended,
                              recomended.difference(user_recomended)))
        favorite_books = user.favorite_books.all().values_list('id', flat=True)

    context = {
        'popular': popular[:MAX_BOOKS_ON_SLIDER],
        'new': new[:MAX_BOOKS_ON_SLIDER],
        'recomended': recomended[:MAX_BOOKS_ON_SLIDER],
        'banners': Banner.objects.filter(close=False),
        'favorite_books': favorite_books
    }
    context.update(main_forms(request))
    return TemplateResponse(request, 'index.html', context)


def search(request, sort=''):
    """Поиск"""
    search_form = SearchForm
    data = request.POST
    search_word = data.get('search_word', '')
    books_list = Book.objects.all()
    sort = data.get('sort', '')
    if search_word:
        if not sort:
            books_name_list = Book.objects.filter(
                name__iregex=search_word
            ).order_by('-buying')
            books_author_list = Book.objects.filter(
                author__iregex=search_word
            ).exclude(id__in=books_name_list.values('id')).order_by('-buying')
            if 'apply_filter' in data:
                books_name_list = filter_books(books_name_list, data)
                books_author_list = filter_books(books_author_list, data)
            books_list = list(chain(books_name_list, books_author_list))
        else:
            books_list = Book.objects.filter(
                Q(author__iregex=search_word) |
                Q(name__iregex=search_word)
            )
        search_form = SearchForm(data=data)

    context = catalog_type(request, books_list, sort)
    context['search_form'] = search_form
    return TemplateResponse(request, 'books/search.html', context)


def catalog(request, sort='min_buying'):
    """Основной каталог"""
    books_list = Book.objects.all()
    context = catalog_type(request, books_list, sort)
    return TemplateResponse(request, 'books/catalog.html', context)


def news(request, sort='min_release'):
    """Каталог новых книг"""
    books_list = Book.objects.filter(
        created__gte=date.today() - timedelta(days=NEWBOOK_DAYS))

    context = catalog_type(request, books_list, sort)
    return TemplateResponse(request, 'books/news.html', context)


def book_detail(
    request,
    book_id,
    book_status=0,
    book_favorite=0,
    user_have_review=False
):
    """Страница книги"""
    user = request.user
    book = get_object_or_404(Book, id=book_id)
    files_format = book.files.all().values_list('name', flat=True)
    reviews = Review.objects.filter(book=book)
    if user.is_authenticated:
        order = user.order.filter(close=False)[0]
        book_status = 2 if user.buyed_books.filter(id=book_id) else 0
        if not book_status:
            book_status = 1 if order.book.filter(id=book_id) else 0
        book_favorite = 1 if user.favorite_books.filter(id=book_id) else 0
        for genre in book.genre.all():
            ViewedGenres.objects.create(user=user, genre=genre)
        user_have_review = reviews.filter(user=user).exists()

    context = {
        'book': book,
        'book_status': book_status,
        'reviews': reviews,
        'book_favorite': book_favorite,
        'files_format': files_format,
        'user_have_review': user_have_review
    }
    context.update(main_forms(request))
    return TemplateResponse(request, 'books/book_detail.html', context)


@login_required
def change_favorite(request, book_favorite=0):
    """Добавление или удаление из избранного на карточках и странице товара"""
    if request.method == "POST":
        user = request.user
        book = get_object_or_404(Book, id=request.POST['book'])
        favorite_books = user.favorite_books.all().filter(id=book.id)
        if favorite_books:
            user.favorite_books.remove(book)
        else:
            user.favorite_books.add(book)
            book_favorite = 1

        context = {
            'book': book,
            'book_favorite': book_favorite,
        }
        if 'button' in request.POST:
            return TemplateResponse(
                request, 'dynamic_forms/favorite_button.html', context
            )
        return TemplateResponse(
            request, 'dynamic_forms/favorite.html', context
        )
    return reverse_lazy('books:index')


@login_required
def change_cart(request, book_status=0):
    """Добавление или удаление из корзины на странице товара"""
    if request.method == "POST":
        user = request.user
        book = get_object_or_404(Book, id=request.POST['book'])
        if user.buyed_books.filter(id=book.id):

            context = {
                'book': book,
                'book_status': 2
            }
            return TemplateResponse(
                request, 'dynamic_forms/cart_button.html', context
            )
        order = user.order.filter(close=False)[0]
        if order.book.filter(id=book.id):
            order.book.remove(book)
        else:
            book_status = 1
            order.book.add(book)

        context = {
            'book': book,
            'book_status': book_status
        }
        return TemplateResponse(
            request, 'dynamic_forms/cart_button.html', context
        )
    return reverse_lazy('books:index')

bookstore/templates/books/book_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% if user.is_authenticated %}
<script>
    // Клик авторизованного по корзине/избранному
    $(document).on("submit", "#cart_form, #favorite_form", function () {
        var form = $(this)
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function (html) {
                form.replaceWith(html)
            }
        });
        return false;
    });
    $(document).on("submit", "#cart_form", function () {
        var form = $('#get_cart_img')
        setTimeout(
            () => {
                $.ajax({
                    url: form.attr('action'),
                    success: function (html) {
                        form.replaceWith(html)
                    }
                });
                return false;
            },
            1000
        );
    });
</script>
<script>
    // Отправка отзыва на сервер. При ошибке (Недостаточно символов) выдает уведомление. При успехе - перезагрузка страницы.
    $(document).ready(function () {
        $('#comment-form').submit(function () {
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function (html) {
                    location.reload(true)
                }
            });
            return false;
        });
    });
</script>
{% endif %}
<div class="row">
    <div class="col-12 background-after" style="height: unset;">
        <div class="row">
            <div class="col-12 mb-3 col-lg-3 order-1">
                <div class="d-flex flex-column justify-content-center">
                    <div id="main_image" class="mb-1 book_images d-flex align-items-center justify-content-center">
                        <img style="width: 100%;" src="{{ book.main_image.url }}" />
                    </div>
                    <div class="w-100 book_other_images d-flex justify-content-around"
                        style="font-weight: 600; font-size: 20px;">
                        <div class="d-flex flex-column align-items-center">
                            <div>
                                <span class="rating-result">★</span>
                                <span>{{ book.score }}</span>
                            </div>
                            <span>оценка</span>
                        </div>
                        <div class="border-line"></div>
                        <div class="d-flex flex-column align-items-center">
                            <span>{{ reviews.count }}</span>
                            <span>отзыва</span>
                        </div>
                        <div class="border-line"></div>
                        <div class="d-flex flex-column align-items-center">
                            <span>{{ book.buying}}</span>
                            <span>куплено</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12 mb-3 col-lg-6 order-3 order-lg-2">
                <div class="d-flex px-2 mb-3 flex-column justify-content-center book_images">
                    <h1>{{ book.name }}</h1>
                    <div class="d-flex flex-column">
                        <span class="me-1" style="font-size:25px;">Авторы:</span>
                        <span style="font-size:20px;">{{ book.author }}</span>
                    </div>
                    <div class="d-flex flex-column">
                        <span style="font-size:25px;">Описание:</span>
                        <span style="font-size:18px;">{{ book.description|linebreaks }}</span>
                    </div>
                    <div class="d-flex flex-column">
                        <span style="font-size:25px;">Характеристики:</span>
                        <span style="font-size:18px;">В книге {{ book.pages }} страниц</span>
                        <span style="font-size:18px;">Выпущена {{ book.release }} г.</span>
                        <span style="font-size:18px;">Добавлена на сайт {{ book.created|date:"d.m.Y" }}</span>
                        <span style="font-size:18px;">Для скачивания доступны: {% for format in files_format %}
                            {{format}}{% if not forloop.last %},{% endif %}{% endfor %}</span>
                    </div>
                </div>
                <div class="mb-3 book_images">
                    <button class="btn w-100 mb-0" style="background-color: #123C69; color: white;" type="button"
                        data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false"
                        aria-controls="collapseExample">
                        Открыть фрагмент для ознакомления
                    </button>
                    <div class="collapse" id="collapseExample">
                        <div class="p-2 w-100">
                            {{ book.fragment|linebreaks }}
                        </div>
                        <button class="btn w-100 mb-0" style="background-color: #123C69; color: white;" type="button"
                            data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false"
                            aria-controls="collapseExample">
                            Закрыть фрагмент для ознакомления
                        </button>
                    </div>
                </div>
                {% if user.is_authenticated %}
                <div class="
                d-flex mb-3 p-2 flex-column justify-content-center book_images
                " {% if user_have_review %} style="display:none !important" {% endif %}>
                    <form id="comment-form" class="d-flex flex-column" method="post"
                        action="{% url 'users:review' book.id %}">
                        {% csrf_token %}
                        <h4>Оставить отзыв:</h4>
                        <div id="comment-form-score" class="rating-area mb-0" style="width: max-content;">
                            <input class="star-rating" type="radio" id="star-5" name="score" checked="checked"
                                value="5">
                            <label for="star-5" title="Оценка «5»"></label>
                            <input class="star-rating" type="radio" id="star-4" name="score" value="4">
                            <label for="star-4" title="Оценка «4»"></label>
                            <input class="star-rating" type="radio" id="star-3" name="score" value="3">
                            <label for="star-3" title="Оценка «3»"></label>
                            <input class="star-rating" type="radio" id="star-2" name="score" value="2">
                            <label for="star-2" title="Оценка «2»"></label>
                            <input class="star-rating" type="radio" id="star-1" name="score" value="1">
                            <label for="star-1" title="Оценка «1»"></label>
                        </div>
                        <div id="comment-form-text" class="w-100 comment-form-text">
                            <textarea class="w-100 rounded-3" name="text"></textarea>
                        </div>
                        <button id="comment-button" type="submit" class="btn" style="background-color: #123C69;">
                            <span style="color: white;">
                                Сохранить
                            </span>
                        </button>
                    </form>
                </div>
                {% endif %}
                <div class="d-flex p-2 flex-column justify-content-center book_images">
                    <h1 class="m-0">Отзывы</h1>
                    {% for review in reviews %}
                    <form class="rounded-3 d-flex flex-column p-3 mt-2" style="border: 2px #BAB2B5 solid" method="post"
                        action="{% url 'users:change_review' book.id review.id  %}">
                        {% csrf_token %}
                        <div class="d-flex justify-content-between">
                            <h5>{{ review.user }}</h5>
                            <div class="rating-result m-0">
                                <span class="{% if review.score >= 1 %}active{% endif %}"></span>
                                <span class="{% if review.score >= 2 %}active{% endif %}"></span>
                                <span class="{% if review.score >= 3 %}active{% endif %}"></span>
                                <span class="{% if review.score >= 4 %}active{% endif %}"></span>
                                <span class="{% if review.score == 5 %}active{% endif %}"></span>
                            </div>
                        </div>
                        <span style="overflow-wrap: break-word;">{{ review.comment }}</span>
                        {% if user == review.user %}
                        <div class="d-flex justify-content-between mt-3">
                            <button type="button" class="btn comment-button-change" style="background-color: #123C69;">
                                <span style="color: white;">
                                    Изменить отзыв
                                </span>
                            </button>
                            <button type="submit" class="btn comment-button-delete" name="delete"
                                style="background-color: #AC3B61;">
                                <span style="color: white;">
                                    Удалить отзыв
                                </span>
                            </button>
                        </div>
                        <input class="review-score" value="{{ review.score }}" hidden>
                        <input class="review-id" value="{{ review.id }}" hidden>
                        {% endif %}
                    </form>
                    {% empty %}
                    <span style="font-size: 18px;">Пока никто не оставил отзыва.</span>
                    {% endfor %}
                </div>
            </div>

            <div class="col-12 mb-3 col-lg-3 order-2 order-lg-3">
                <div class="d-flex p-2 flex-column align-items-center justify-content-center book_images">
                    <h1>{{ book.get_price }} ₽</h1>
                    <div class="d-flex w-100 justify-content-between">
                        {% if book.discount > 0 %}
                        <h3 style="text-decoration: line-through;">{{book.price}} ₽</h3>
                        <h4 style="color: #AC3B61;">–{{ book.discount }}%</h4>
                        {% endif %}
                    </div>
                    {% include 'dynamic_forms/cart_button.html' %}
                    {% include 'dynamic_forms/favorite_button.html' %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Изменение или удаление отзыва
    $(function () {
        $('.comment-button-change').click(function () {
            form = $(this).parent().parent()
            review_id = form.children('.review-id').val()
            score_value = '#star-' + form.children('.review-score').val()

            score_form = $('#comment-form-score').clone().removeAttr('id')
            score_form.children('#star-5').removeAttr('checked')
            score_form.children(score_value).attr('checked', 'checked')

            all_input_score = score_form.find('input')
            all_label_score = score_form.find('label')
            for (let i = 0; i < 5; i++) {
                id = all_input_score.eq(i).attr('id')
                all_input_score.eq(i).attr('id', id + review_id)
                all_label_score.eq(i).attr('for', id + review_id)
            }

            comment_form = $('#comment-form-text').clone().removeAttr('id')
            button_form = $('#comment-button').clone().removeAttr('id')


            comment_text = form.children('span').text()

            form.children().children('.rating-result').replaceWith(score_form)
            form.children('span').replaceWith(comment_form)
            form.children('.comment-form-text').children('textarea').val(comment_text)
            $(this).replaceWith(button_form)
        });
    });
</script>
{% endblock %}

bookstore/templates/books/catalog.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-12 background-after" style="min-height: 800px; height: unset;">
        <div class="row">
            <div class="col-12 col-lg-3">
                <button class="mobile-filters-button btn btn-light w-100 mb-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#filters" aria-expanded="false" aria-controls="filters">
                    <span>Фильтры</span>
                </button>
                <form id="filters" class="accordion collapse navbar-collapse mobile-filters" method="post"
                    action="{% block catalog_url %}{% url 'books:catalog' %}{% endblock %}">
                    {% include 'books/includes/filters.html' %}
                </form>
            </div>
            <div class="col-12 offset-0 col-lg-9">
                <button class="mobile-filters-button btn btn-light w-100 mb-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#sort_links" aria-expanded="false" aria-controls="sort_links">
                    <span>Сортировка</span>
                </button>
                <div id="sort_links"
                    class="accordion collapse navbar-collapse justify-content-between px-3 mb-4 py-1 rounded-2 sort_links"
                    style="background-color: #BAB2B5;">
                    <div class="dropdown">
                        <button id="{{ min_buying }}{{ min_score }}" class="btn btn-secondary dropdown-toggle"
                            type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"
                            style="background-color: unset; color: black; border: unset;">
                            По известности
                        </button>
                        <ul class="dropdown-menu px-3" aria-labelledby="dropdownMenuButton1">
                            <li><a id="{{ min_buying }}" class="sort" name="min_buying" href="#">
                                    <span>Популярнее</span></a></li>
                            <li><a id="{{ min_score }}" class="sort" name="min_score" href="#"><span>По
                                        рейтингу</span></a></li>
                        </ul>
                    </div>
                    <div>
                        <span id="{{ min_total_price }}{{ total_price }}">По цене</span>
                        {% if min_total_price %}
                        <a class="sort" name="total_price" href="#"><img src="{% static 'icons/arrow.svg' %}"></img></a>
                        {% else %}
                        <a class="sort" name="min_total_price" href="#"><img src="{% static 'icons/arrow.svg' %}"
                                style="transform: rotate(180deg)"></img></a>

                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    {% for book in page_obj %}
                    <div class="col-6 col-lg-3 mb-3">
                        {% include 'books/includes/catalog_card.html' %}
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    // Клик по сотрировке отправляет форму
    $(function () {
        $('.sort').click(function () {
            sort_name = $(this).attr('name')
            $('#sort_input').attr('value', sort_name)
            $('#apply_filter_button').click()
        });
    });
</script>
{% endblock %}

bookstore/templates/books/news.html
{% extends 'books/catalog.html' %}
{% load static %}
{% block catalog_name %}
Новинки
{% endblock %}
{% block catalog_url %}
{% url 'books:news' %}
{% endblock %}

bookstore/templates/books/search.html
{% extends 'books/catalog.html' %}
{% load static %}
{% block catalog_name %}
Поиск
{% endblock %}
{% block catalog_url %}
{% url 'books:search' %}
{% endblock %}