bookstore/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path(
        '', views.index, name='index'
    ),
    path(
        'catalog', views.catalog, name='catalog'
    ),
    path(
        'news', views.news, name='news'
    ),
    path(
        'change_favorite', views.change_favorite, name='change_favorite'
    ),
    path(
        'change_cart', views.change_cart, name='change_cart'
    ),
    path(
        'search', views.search, name='search'
    ),
    path(
        'book/<int:book_id>/', views.book_detail, name='book'
    ),

]

bookstore/bookstore/urls.py
from django.conf import settings
from django.views.static import serve as mediaserve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('my/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

bookstore/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path(
        'login', views.login, name='login'
    ),
    path(
        'logout', views.logout, name='logout'
    ),
    path(
        'signup', views.signup, name='signup'
    ),
    path(
        'favorite', views.favorite, name='favorite'
    ),
    path(
        'review/<int:book_id>/', views.create_review, name='review'
    ),
    path(
        'review/<int:book_id>/<int:review_id>/',
        views.change_review,
        name='change_review'
    ),
    path(
        'profile', views.profile, name='profile'
    ),
    path(
        'cart', views.cart, name='cart'
    ),
    path(
        'cart/<int:buy>/', views.cart, name='cart'
    ),
    path(
        'take_cart_img', views.take_cart_img, name='take_cart_img'
    ),
    path(
        'payment', views.payment, name='payment'
    ),
    path(
        'library', views.library, name='library'
    ),
    path(
        'get_book/<int:book_id>/<str:format>', views.get_book, name='get_book'
    ),
]

bookstore/templates/includes/cart_img.html
{% load static %}
<form id="get_cart_img" method="get" action="{% url 'users:take_cart_img' %}">
    <img src="{% if order_full %}{% static 'icons/cart_full.svg' %}{% else %}{% static 'icons/cart.svg' %}{% endif %}"
        class="icon-img nav-icon" alt="cart icon"></img>
</form>

bookstore/templates/includes/footer.html
<div class="container">
    <div class="row pt-3 pb-3">
        <div class="col-md-4 offset-md-2 col-6 offset-0 d-flex flex-column justify-content-end center">
            <a class="fs-3 text-reset d-flex mb-1" data-bs-toggle="tooltip" data-bs-placement="bottom"
                title="Перейти на главную страницу" href="{% url 'books:index'%}">Bookstore
            </a>
            <span>Контакты для связи:</span>
            <div class="mb-2">
                <a href="https://vk.com/" target="_blank">ВКонтакте</a>
                <a href="https://t.me/" target="_blank">Telegram</a>
            </div>
            <span>© 2024. Все права защищены. Магазин создавался для учебных целей и не предоставляет платных услуг. Все
                книги, которые находятся на этом сайте, можно найти в свободном доступе в интернете.</span>
        </div>
        <div class="col-md-4 offset-md-2 col-6 offset-0 d-flex flex-column justify-content-end"
            style="word-wrap:break-word;">
            <span>+ 7 (908) 211 45 41</span>
            <span>dch02abonent68@gmail.com</span>
            <span>ул. Академика Киренского, 26Б, Красноярск, Красноярский край, 660074</span>
        </div>
    </div>
</div>

bookstore/templates/includes/header.html
{% load static %}
{% if user.is_authenticated %}
<script>
    // Добавление в избранное
    $(document).on("submit", ".add_favorite_form", function () {
        var form = $(this)
        var name = $(this).attr('name')
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function (html) {
                $('form[name=' + name + ']').each(function () {
                    $(this).replaceWith(html)
                });

            }
        });
        return false;
    });
</script>
{% else %}
<script>
    // Передача данных модальной формы на сервер
    $(document).on("submit", "#login-form, #signup-form", function () {
        name = $(this).attr('name')
        $parent = $(this).parent()
        $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            success: function (html) {
                if (html['login']) {
                    location.reload(true)
                }
                else {
                    $('#' + name + '-form').remove()
                    $parent.append(html)
                }
            },

        });
        return false;
    });
</script>
<script>
    // Добавление в избранное неавторизованым выдает сообщение
    // Клик неавторизованного по корзине/избранному/библиотеке выдает сообщение
    $(function () {
        $('#favorites, #cart, #library, .favorite-button').click(function () {
            var toastElList = [].slice.call(document.querySelectorAll('.toast'))
            console.log(toastElList)
            var toastList = toastElList.map(function (toastEl) {
                return new bootstrap.Toast(toastEl)
            })
            console.log(toastList)
            toastList.forEach(toast => toast.show())
            return false
        });
    });
</script>
{% for _ in '01' %}
<div class="modal fade modal-fullscreen col-12" {% if forloop.first %} id="Login" aria-labelledby="Login" {% else %}
    id="Signup" aria-labelledby="Signup" {% endif %} tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body d-flex flex-column align-items-end">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="myform w-100">
                    {% if forloop.first %}
                    <h1 class="text-center h1style">Авторизация</h1>
                    {% include 'dynamic_forms/auth.html' %}
                    {% else %}
                    <h1 class="text-center h1style">Регистрация</h1>
                    {% include 'dynamic_forms/signup.html' %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true"
    style="position: absolute; top: 10px; right: 10px; z-index: 2000;">
    <div class="d-flex">
        <div class="toast-body">
            Войдите или зарегистрируйтесь!
        </div>
        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Закрыть"></button>
    </div>
</div>
{% endif %}
<nav class="navbar navbar-expand-lg navbar-dark fixed-top navbarstyle">
    <div id="top_flex lg-header-panel" class="container-fluid">
        <button class="navbar-toggler shadow-none border-0 col-2 pt-1" type="button" data-bs-toggle="collapse"
            data-bs-target=".multi-collapse" aria-controls="BooksLinks ProfileLinks" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="fs-5 text-light d-flex justify-content-center col-4 offset-2 offset-lg-0 col-lg-1 order-1"
            data-bs-toggle="tooltip" data-bs-placement="bottom" title="Перейти на главную страницу"
            href="{% url 'books:index'%}">Bookstore
        </a>
        <a class="nav-link d-flex text-reset flex-column align-items-center pb-1 col-2 offset-2 d-lg-none order-2 blank_space"
            {% if user.is_authenticated %} href="{% url 'users:profile'%}" title="Профиль" {% else %}
            data-bs-toggle="modal" data-bs-target="#Login" href="{% url 'users:profile'%}"
            title="Войти или зарегистрироваться" blank_space {% endif %}>
            <img src="{% static 'icons/profile.svg' %}" class="icon-img nav-icon" alt="profile icon"></img>
        </a>
        <div class="collapse multi-collapse navbar-collapse show order-2 col-lg-6" id="BooksLinks">
            <div class="row d-flex flex-fill align-items-center">
                <div class="order-2 col-lg-8">
                    <div class="d-flex input-group">
                        <form
                            class="w-100 align-items-center justify-content-center shadow-none border-0 lg-me-3 d-flex"
                            style="background-color: white; border-radius: 10px;" method="post"
                            enctype="multipart/form-data" action="{% url 'books:search'%}">
                            {% csrf_token %}
                            {% for field in search_form %}
                            {{ field }}
                            <span class="input-group-append">
                                <button type="submit" class="btn search_icon shadow-none border-0 d-none d-lg-block"
                                    data-bs-toggle="tooltip" data-bs-placement="bottom"
                                    title="Нажмите, чтобы начать поиск">
                                    <img src="{% static 'icons/loupe.svg' %}" class="icon-img nav-icon"
                                        alt="profile icon"></img>
                                </button>
                            </span>
                            {% endfor %}
                        </form>
                    </div>
                </div>
                <div class="d-flex justify-content-around order-1 d-flex col-lg-4">
                    <a class="nav-link text-light lg-ms-3 lg-me-3" style="font-size: 18px;"
                        href="{% url 'books:news'%}">Новинки</a>
                    <a class="nav-link text-light" style="font-size: 18px;" href="{% url 'books:catalog'%}">Каталог</a>
                </div>
            </div>
        </div>
        <div class="collapse multi-collapse navbar-collapse col-lg-3 order-4" id="ProfileLinks">
            <div class="d-flex justify-content-around d-flex justify-content-between w-100">
                <a id="library" class="nav-link d-flex text-reset flex-column align-items-center lg-me-3"
                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="Просмотр купленных книг"
                    href="{% url 'users:library'%}">
                    <img src="{% static 'icons/library.svg' %}" class="icon-img nav-icon" alt="library icon"></img>
                    <span class="d-sm-inline text-white">Библиотека</span>
                </a>
                <a id="favorites" class="nav-link d-flex text-reset flex-column align-items-center lg-me-3"
                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="Просмотр избранного"
                    href="{% url 'users:favorite' %}">
                    <img src="{% static 'icons/favorite.svg' %}" class="icon-img nav-icon" alt="favorite icon"></img>
                    <span class="d-sm-inline text-white">Избранное</span>
                </a>
                <a id="cart" class="nav-link d-flex text-reset flex-column align-items-center lg-me-3"
                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="Перейти в корзину"
                    href="{% url 'users:cart' %}">
                    {% include 'includes/cart_img.html' %}
                    <span class="d-sm-inline text-white">Корзина</span>
                </a>
                <a class="nav-link d-flex text-reset flex-column align-items-center d-none d-lg-flex blank_space blank_space"
                    {% if user.is_authenticated %} href="{% url 'users:profile'%}" title="Профиль" {% else %}
                    data-bs-toggle="modal" data-bs-target="#Login" href="#Login" title="Войти или зарегистрироваться"
                    blank_space {% endif %}>
                    <img src="{% static 'icons/profile.svg' %}" class="icon-img nav-icon" alt="profile icon"></img>
                    <span class="d-sm-inline text-white ">
                        {% if user.is_authenticated %}Профиль{% else %}Войти{% endif %}
                    </span>
                </a>
            </div>
        </div>
    </div>
</nav>

bookstore/templates/includes/paginator.html
{% load static %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="paginator-pages d-flex justify-content-center mt-3">
  {% if page_obj.has_previous %}
  <a class="page-item" href="?page=1">
    <span>...</span>
  </a>
  {% endif %}
  {% for i in page_obj.paginator.page_range %}
  {% if page_obj.number == i %}
  <div class="page-item active">
    <span>{{ i }}</span>
  </div>
  {% else %}
  <a class="page-item" href="?page={{ i }}">
    <span>{{ i }}</span>
  </a>
  {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
  <a class="page-item" href="?page={{ page_obj.paginator.num_pages }}">
    <span>...</span>
  </a>
  {% endif %}
</nav>
{% endif %}

bookstore/templates/includes/settings.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"
    type='text/css'>

<link href="{% static 'icons/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
<link href="{% static 'css/owl.theme.default.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>