bookstore/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path(
        '', views.index, name='index'
    ),
    path(
        'catalog', views.catalog, name='catalog'
    ),
    path(
        'news', views.news, name='news'
    ),
    path(
        'change_favorite', views.change_favorite, name='change_favorite'
    ),
    path(
        'change_cart', views.change_cart, name='change_cart'
    ),
    path(
        'search', views.search, name='search'
    ),
    path(
        'book/<int:book_id>/', views.book_detail, name='book'
    ),

]

bookstore/bookstore/urls.py
from django.conf import settings
from django.views.static import serve as mediaserve
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('my/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

bookstore/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [

    path(
        'login', views.login, name='login'
    ),
    path(
        'logout', views.logout, name='logout'
    ),
    path(
        'signup', views.signup, name='signup'
    ),
    path(
        'favorite', views.favorite, name='favorite'
    ),
    path(
        'review/<int:book_id>/', views.create_review, name='review'
    ),
    path(
        'review/<int:book_id>/<int:review_id>/',
        views.change_review,
        name='change_review'
    ),
    path(
        'profile', views.profile, name='profile'
    ),
    path(
        'cart', views.cart, name='cart'
    ),
    path(
        'cart/<int:buy>/', views.cart, name='cart'
    ),
    path(
        'take_cart_img', views.take_cart_img, name='take_cart_img'
    ),
    path(
        'payment', views.payment, name='payment'
    ),
    path(
        'library', views.library, name='library'
    ),
    path(
        'get_book/<int:book_id>/<str:format>', views.get_book, name='get_book'
    ),
]

bookstore/templates/dynamic_forms/auth.html
<form id="login-form" method="post" action="{% url 'users:login' %}" name="login">
    {% for error in auth_form.non_field_errors %}
    <div class="alert alert-danger">
        {{ error|escape }}
    </div>
    {% endfor %}
    {% csrf_token %}
    {% for field in auth_form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
        {{ error|escape }}
    </div>
    {% endfor %}
    <div class="mb-3">
        <label for="LoginInput" class="form-label">{{ field.label }}</label>
        {{ field }}
        <!-- <input type="text" class="form-control text-white" id="LoginInput" name="username" aria-describedby="emailHelp"> -->
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-light mt-1 mb-3 shadow-none border-0">Войти</button>
    <p class="pstyle">Не зарегистрированы?
        <a class="astyle" data-bs-target="#Signup" data-bs-toggle="modal" data-bs-dismiss="modal"
            style="cursor: pointer;">Зарегистрируйтесь прямо
            сейчас!</a>
    </p>
</form>

bookstore/templates/dynamic_forms/cart.html
{% load static %}
{% if user.is_authenticated %}
<form id="cart_form" class="w-100" method="post" action="{% url 'books:change_cart'%}">
    {% csrf_token %}
    {% if book_status == 1 %}
    <button class="w-100 btn shadow-none border-0" style="background-color: #AC3B61;">
        <span style="color:white">В корзине</span>
    </button>
    {% elif book_status == 2 %}
    <div class="w-100 btn shadow-none border-0">
        <span style="color:black">Уже куплено</span>
    </div>
    {% else %}
    <button class="w-100 btn shadow-none border-0" style="background-color: #123C69;">
        <span style="color:white">Добавить в корзину</span>
    </button>
    {% endif %}
    <input name="book" value="{{ book.id }}" hidden>
</form>
{% else %}
<div class="w-100 btn shadow-none border-0">
    <span style="color:black">Войдите или зарегистрируйтесь для покупки</span>
</div>
{% endif %}

bookstore/templates/dynamic_forms/cart_button.html
{% load static %}
{% if user.is_authenticated %}
<form id="cart_form" class="w-100" method="post" action="{% url 'books:change_cart'%}">
    {% csrf_token %}
    {% if book_status == 1 %}
    <button class="w-100 btn shadow-none border-0" style="background-color: #BAB2B5;">
        <span style="color:black">В корзине</span>
    </button>
    {% elif book_status == 2 %}
    <div class="w-100 btn shadow-none border-0">
        <span style="color:black">Уже куплено</span>
    </div>
    {% else %}
    <button class="w-100 btn shadow-none border-0" style="background-color: #123C69;">
        <span style="color:white">Добавить в корзину</span>
    </button>
    {% endif %}
    <input name="book" value="{{ book.id }}" hidden>
</form>
{% else %}
<div class="w-100 btn shadow-none border-0">
    <span style="color:black">Войдите или зарегистрируйтесь для покупки</span>
</div>
{% endif %}

bookstore/templates/dynamic_forms/favorite.html
{% load static %}
<form class="add_favorite_form" name="{{ book.id }}" method="post" action="{% url 'books:change_favorite'%}">
    {% csrf_token %}
    <input value="{{ book.id }}" name="book" hidden>
    <button class="favorite-button">
        {% if book.id in favorite_books or book_favorite == 1 %}
        <img src="{% static '/icons/del_favorite.svg' %}">
        {% else %}
        <img src="{% static '/icons/add_favorite.svg' %}">
        {% endif %}
    </button>
</form>

bookstore/templates/dynamic_forms/favorite_button.html
{% load static %}
{% if user.is_authenticated %}
<form id="favorite_form" class="w-100 mt-1" method="post" action="{% url 'books:change_favorite'%}">
    {% csrf_token %}
    {% if book_favorite == 0 %}
    <button class="w-100 btn shadow-none border-0" style="background-color: #AC3B61;">
        <span style="color:white">В избранное</span>
    </button>
    {% else %}
    <button class="w-100 btn shadow-none border-0" style="background-color: #EDC7B7">
        <span style="color:black">В избранном</span>
    </button>
    {% endif %}
    <input name="book" value="{{ book.id }}" hidden>
    <input name="button" value="1" hidden>
</form>
{% endif %}

bookstore/templates/dynamic_forms/signup.html
<form id="signup-form" method="post" action="{% url 'users:signup' %}" name="signup">
    {% for error in signup_form.non_field_errors %}
    <div class="alert alert-danger">
        {{ error|escape }}
    </div>
    {% endfor %}
    {% csrf_token %}
    {% for field in signup_form %}
    {% for error in field.errors %}
    <div class="alert alert-danger">
        {{ error|escape }}
    </div>
    {% endfor %}
    <div class="mb-3">
        <label for="SignupInput" class="form-label">{{ field.label }}</label>
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-light mt-1 mb-3 shadow-none border-0">Зарегистрироваться</button>
    <p class="pstyle">Зарегистрированы?
        <a class="astyle" data-bs-target="#Login" data-bs-toggle="modal" data-bs-dismiss="modal"
            style="cursor: pointer;">Войти</a>
    </p>
</form>